# Generated by Django 4.2.4 on 2023-08-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_songs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='user',
        ),
    ]
